### ISSUE TITLE
Compile in OSX

### ISSUE THREAD

**Issue by drtaglia** [thegrandpoobah/voronoi#25]
remove VoronoiDiagramGenerator:: in VoronoiDiagramGenerator.h from the methods already in the class.

Also, this is a bit sad:

    ~/build/voronoi: make
    /usr/local/bin/g++-4.8  -fopenmp -O2 -L/usr/local/lib/ -o voronoi_stippler picopng/picopng.o     stippler/bitmap.o stippler/stippler_api.o stippler/stippler.o stippler/VoronoiDiagramGenerator.o    voronoi/parse_arguments.o voronoi/voronoi.o -lboost_program_options
    ~/build/voronoi: ./voronoi_stippler -s 16000 -I corpus/klaymen.png -O test.svg
    voronoi_stippler(77937) malloc: *** error for object 0x10365c570: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

**Comment by thegrandpoobah** [comment]
This was fixed by 8ef7a04 which now defaults to using Clang in OS X along with better documentation of the build process in the readme.md file.
